### ISSUE TITLE
It will be great if installing serverless npm package can be added in the readme

### ISSUE THREAD

**Issue by MishalValiyakath** [danielzotti/aws-lambda-layers-test#2]
It will be great if installing serverless npm package can be added in the readme

**Comment by danielzotti** [comment]
Thanks for your interesting in this repo! It has been created for people who are already comfortable with AWS and Serverless Framework and it's focused on "lambda layer" feature. Anyway, I've solved the issue with this commit: https://github.com/danielzotti/aws-lambda-layers-test/commit/80e56c8fedbdae7b74959b3e92fb07d5095465e0
